// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerShared.DbContexts;

#nullable disable

namespace ServerShared.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260105143411_NewStart")]
    partial class NewStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerShared.DbContexts.AchievementsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GachaCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AchievementsData");
                });

            modelBuilder.Entity("ServerShared.DbContexts.CompletedAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievementCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("UserInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("CompletedAchievement");
                });

            modelBuilder.Entity("ServerShared.DbContexts.GameCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("A_Skill_Level")
                        .HasColumnType("int");

                    b.Property<int>("B_Skill_Level")
                        .HasColumnType("int");

                    b.Property<string>("CharacterID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EXP")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("StarLevel")
                        .HasColumnType("int");

                    b.Property<int?>("UserInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("GameCharacters");
                });

            modelBuilder.Entity("ServerShared.DbContexts.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("ServerShared.DbContexts.RequestMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MissionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.ToTable("RequestMissions");
                });

            modelBuilder.Entity("ServerShared.DbContexts.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementDataId")
                        .HasColumnType("int");

                    b.Property<int>("Crystal")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementDataId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("ServerShared.DbContexts.CompletedAchievement", b =>
                {
                    b.HasOne("ServerShared.DbContexts.UserInfo", null)
                        .WithMany("CompletedAchievements")
                        .HasForeignKey("UserInfoId");
                });

            modelBuilder.Entity("ServerShared.DbContexts.GameCharacter", b =>
                {
                    b.HasOne("ServerShared.DbContexts.UserInfo", null)
                        .WithMany("Characters")
                        .HasForeignKey("UserInfoId");
                });

            modelBuilder.Entity("ServerShared.DbContexts.RequestMission", b =>
                {
                    b.HasOne("ServerShared.DbContexts.UserInfo", null)
                        .WithMany("RequestMissions")
                        .HasForeignKey("UserInfoId");
                });

            modelBuilder.Entity("ServerShared.DbContexts.UserInfo", b =>
                {
                    b.HasOne("ServerShared.DbContexts.AchievementsData", "AchievementData")
                        .WithMany()
                        .HasForeignKey("AchievementDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchievementData");
                });

            modelBuilder.Entity("ServerShared.DbContexts.UserInfo", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("CompletedAchievements");

                    b.Navigation("RequestMissions");
                });
#pragma warning restore 612, 618
        }
    }
}
