// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerShared.DbContexts;

#nullable disable

namespace ServerShared.Migrations.GameDB
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260413121421_AddGameEventShardColumn")]
    partial class AddGameEventShardColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServerShared.DbContexts.AchievementsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GachaCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AchievementsData");
                });

            modelBuilder.Entity("ServerShared.DbContexts.CompletedAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AchievementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("RewardCheckPoint")
                        .HasColumnType("int");

                    b.Property<int?>("UserAccountDetailUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountDetailUserId");

                    b.ToTable("CompletedAchievement");
                });

            modelBuilder.Entity("ServerShared.DbContexts.GameCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("A_Skill_Level")
                        .HasColumnType("int");

                    b.Property<int>("B_Skill_Level")
                        .HasColumnType("int");

                    b.Property<int>("EXP")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("StarLevel")
                        .HasColumnType("int");

                    b.Property<int?>("UserAccountDetailUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountDetailUserId");

                    b.ToTable("GameCharacters");
                });

            modelBuilder.Entity("ServerShared.DbContexts.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shard")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("ServerShared.DbContexts.GameItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserAccountDetailUserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserMailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountDetailUserId");

                    b.HasIndex("UserMailId");

                    b.ToTable("GameItem");
                });

            modelBuilder.Entity("ServerShared.DbContexts.RecordItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StarLevel")
                        .HasColumnType("int");

                    b.Property<int?>("UserAccountDetailUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountDetailUserId");

                    b.ToTable("RecordItem");
                });

            modelBuilder.Entity("ServerShared.DbContexts.RequestMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MissionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserAccountDetailUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountDetailUserId");

                    b.ToTable("RequestMissions");
                });

            modelBuilder.Entity("ServerShared.DbContexts.UserAccountDetail", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AchievementDataId")
                        .HasColumnType("int");

                    b.Property<int>("Crystal")
                        .HasColumnType("int");

                    b.Property<string>("GameState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ReceievedUserRewards")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("AchievementDataId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("ServerShared.DbContexts.UserMail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserAccountDetailUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountDetailUserId");

                    b.ToTable("UserMail");
                });

            modelBuilder.Entity("ServerShared.DbContexts.CompletedAchievement", b =>
                {
                    b.HasOne("ServerShared.DbContexts.UserAccountDetail", null)
                        .WithMany("CompletedAchievements")
                        .HasForeignKey("UserAccountDetailUserId");
                });

            modelBuilder.Entity("ServerShared.DbContexts.GameCharacter", b =>
                {
                    b.HasOne("ServerShared.DbContexts.UserAccountDetail", null)
                        .WithMany("Characters")
                        .HasForeignKey("UserAccountDetailUserId");
                });

            modelBuilder.Entity("ServerShared.DbContexts.GameItem", b =>
                {
                    b.HasOne("ServerShared.DbContexts.UserAccountDetail", null)
                        .WithMany("GameItems")
                        .HasForeignKey("UserAccountDetailUserId");

                    b.HasOne("ServerShared.DbContexts.UserMail", null)
                        .WithMany("Items")
                        .HasForeignKey("UserMailId");
                });

            modelBuilder.Entity("ServerShared.DbContexts.RecordItem", b =>
                {
                    b.HasOne("ServerShared.DbContexts.UserAccountDetail", null)
                        .WithMany("Records")
                        .HasForeignKey("UserAccountDetailUserId");
                });

            modelBuilder.Entity("ServerShared.DbContexts.RequestMission", b =>
                {
                    b.HasOne("ServerShared.DbContexts.UserAccountDetail", null)
                        .WithMany("RequestMissions")
                        .HasForeignKey("UserAccountDetailUserId");
                });

            modelBuilder.Entity("ServerShared.DbContexts.UserAccountDetail", b =>
                {
                    b.HasOne("ServerShared.DbContexts.AchievementsData", "AchievementData")
                        .WithMany()
                        .HasForeignKey("AchievementDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AchievementData");
                });

            modelBuilder.Entity("ServerShared.DbContexts.UserMail", b =>
                {
                    b.HasOne("ServerShared.DbContexts.UserAccountDetail", null)
                        .WithMany("MailBox")
                        .HasForeignKey("UserAccountDetailUserId");
                });

            modelBuilder.Entity("ServerShared.DbContexts.UserAccountDetail", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("CompletedAchievements");

                    b.Navigation("GameItems");

                    b.Navigation("MailBox");

                    b.Navigation("Records");

                    b.Navigation("RequestMissions");
                });

            modelBuilder.Entity("ServerShared.DbContexts.UserMail", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
